version: '3'

services:
  proxy-node-gateway:
    image: govukverify/proxy-node-gateway
    ports:
      - "6100:80"
      - "6601:6601"
    environment:
      PORT: 80
      PROXY_NODE_ENTITY_ID: https://dev-hub.local
      PROXY_NODE_AUTHN_REQUEST_ENDPOINT: http://localhost:6100/SAML2/SSO/POST
      PROXY_NODE_RESPONSE_ENDPOINT: http://localhost:6100/SAML2/SSO/Response/POST
      HUB_URL: http://localhost:6200/stub-idp-demo/SAML2/SSO
      HUB_METADATA_URL: http://proxy-node-metadata/metadata_for_hub.xml
      PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL: http://proxy-node-metadata/metadata_for_connector_node.xml
      CONNECTOR_NODE_URL: http://localhost:5000/SAML2/Response/POST
      CONNECTOR_NODE_ISSUER_ID: http://localhost:5000/Metadata
      CONNECTOR_NODE_METADATA_URL: http://stub-connector/Metadata
      CONNECTOR_NODE_ENTITY_ID: http://localhost:5000/Metadata
      METADATA_REFRESH_DELAY: 10000
      TRANSLATOR_URL: http://proxy-node-translator/SAML2/SSO/Response/POST
      REDIS_SERVER_URI: redis://gateway-redis:6379/
    env_file: ./.local_pki/proxy_node.env
    volumes:
      - ./.local_pki:/verify-eidas-proxy-node/pki:ro
  proxy-node-translator:
    depends_on:
      - soft-hsm
    build:
      context: .
      dockerfile: translator.softHSM.Dockerfile
      args:
        component: proxy-node-translator
        softHSMSigningKeyLabel: vfpn-uk-signing
        softHSMSigningKeyToken: vfpn-uk-signing
        softHSMSigningKeySlot: 0
        softHSMSigningKeyId: DEF0
        softHSMSigningKeyPin: CHANGE-ME-123
        softHSMSigningKeySoPin: CHANGE-ME-456
    image: govukverify/proxy-node-translator
    ports:
      - "6300:80"
      - "6661:6661"
    environment:
      PORT: 80
      PROXY_NODE_ENTITY_ID: https://dev-hub.local
      PROXY_NODE_RESPONSE_ENDPOINT: http://localhost:6100/SAML2/SSO/Response/POST
      HUB_URL: http://localhost:6200/stub-idp-demo/SAML2/SSO
      HUB_METADATA_URL: http://proxy-node-metadata/metadata_for_hub.xml
      PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL: http://proxy-node-metadata/metadata_for_connector_node.xml
      CONNECTOR_NODE_URL: http://localhost:5000/SAML2/Response/POST
      CONNECTOR_NODE_ISSUER_ID: http://localhost:5000/Metadata
      CONNECTOR_NODE_METADATA_URL: http://stub-connector/Metadata
      CONNECTOR_NODE_ENTITY_ID: http://localhost:5000/Metadata
      REDIS_SERVER_URI: redis://gateway-redis:6379/
      SOFT_HSM_LIB_PATH: /usr/lib/softhsm/libsofthsm2.so
    env_file: ./.local_pki/proxy_node.env
    volumes:
      - ./pki:/verify-eidas-proxy-node/pki:ro
  soft-hsm:
    build:
      context: .
      dockerfile: softHSM.baseImage.Dockerfile
      args:
        baseImage: openjdk:11-jre-slim
    image: govukverify/soft-hsm
  stub-connector:
    image: govukverify/stub-connector
    ports:
      - "5000:80"
      - "6667:6667"
    environment:
      PORT: 80
      CONNECTOR_NODE_BASE_URL: http://localhost:5000
      PROXY_NODE_METADATA_FOR_CONNECTOR_NODE_URL: http://proxy-node-metadata/metadata_for_connector_node.xml
      PROXY_NODE_ENTITY_ID: http://proxy-node
    env_file: ./.local_pki/stub_connector.env
    volumes:
      - ./.local_pki:/verify-eidas-proxy-node/pki:ro

  stub-idp:
    image: govukverify/stub-idp
    ports:
      - "6200:80"
    environment:
      PORT: 80
      CONFIG_FILE: ./stub-idp.yml
      LOG_PATH: ./logs
      STUB_IDP_BASIC_AUTH: 'true'
      STUB_IDPS_FILE_PATH: ./stub-idps.yml
      METADATA_URL: http://proxy-node-metadata/metadata_for_hub.xml
      TRUSTSTORE_PASSWORD: marshmallow
      GRADLE_OPTS: "-Xmx64m -Dorg.gradle.jvmargs='-Xmx128m -XX:MaxPermSize=64m'"
      KEY_TYPE: encoded
      CERT_TYPE: encoded
      TRUSTSTORE_TYPE: encoded
      GRAPHITE_REPORTING_FREQUENCY: 24h
      DB_URI: jdbc:postgresql://stub-idp-postgres:5432/postgres?user=postgres&password=password
    env_file: ./.local_pki/stub_idp.env
    volumes:
      - ./stub-idp/resources/stub-idps.yml:/stub-idp/stub-idps.yml:ro
      - ./.local_pki:/stub-idp/pki:ro

  proxy-node-metadata:
    image: ruby:2.5.3-alpine
    command: ruby -run -ehttpd /srv -p80
    ports:
      - "7000:80"
    volumes:
      - ./.local_pki:/srv:ro

  stub-idp-postgres:
    image: postgres
    expose:
      - "5432"

  gateway-redis:
    image: redis:latest
    expose:
      - "6379"
