version: '3'

services:
  proxy-node-gateway:
    image: govukverify/proxy-node-gateway:latest
    build:
      context: .
      args:
        component: proxy-node-gateway
  proxy-node-translator:
    image: govukverify/proxy-node-translator:latest
    build:
      context: .
      args:
        component: proxy-node-translator
  stub-connector:
    image: govukverify/stub-connector:latest
    build:
      context: .
      args:
        component: stub-connector
  softhsm:
    image: govukverify/softhsm:latest
    build:
      context: ./softhsm
