version: '3'

services:
  proxy-node-gateway:
    image: govukverify/proxy-node-gateway:latest
    build:
      context: .
      args:
        component: proxy-node-gateway
  proxy-node-translator:
    image: govukverify/proxy-node-translator:latest
    build:
      context: .
      dockerfile: proxy-node-translator/Dockerfile
  stub-connector:
    image: govukverify/stub-connector:latest
    build:
      context: .
      args:
        component: stub-connector
  eidas-saml-provider:
    image: govukverify/eidas-saml-provider:latest
    build:
      context: .
      args:
        component: eidas-saml-provider
  softhsm:
    image: govukverify/softhsm:latest
    build:
      context: ./softhsm
