apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-gateway-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Release.Name }}-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
{{- if .Values.global.qwacCertificate.enabled }}
  - {{ include "gateway.host.govuk" . }}
{{- else }}
  - {{ include "gateway.host" . }}
{{- end -}}
  gateways:
  - {{ .Release.Name }}-gateway-ingress
  http:
    - route:
      - destination:
          host: {{ .Release.Name }}-gateway
          port:
            number: 80
  exportTo:
  - "."
